"""Stable domain contracts shared across GoldSwingTraderAI subsystems."""

from goldswingtraderai.domain.enums import (
    AccountMode,
    BreakState,
    CandleSequenceState,
    DataQuality,
    Direction,
    ExecutionState,
    ExtensionState,
    HardDecision,
    MarketState,
    MomentumPhase,
    NewsSafetyState,
    OpportunityStage,
    PositionOwnership,
    RiskState,
    RuntimeRole,
    StrategyFamily,
    StructureState,
    SwingRole,
    SwingSide,
    Timeframe,
    TradeManagerAction,
    VolatilityState,
)
from goldswingtraderai.domain.ids import EntityId
from goldswingtraderai.domain.market import (
    AccountFacts,
    Candle,
    CandleSeries,
    MarketSnapshot,
    Quote,
    SymbolSpec,
)
from goldswingtraderai.domain.models import (
    ControllerLease,
    DemoGuardResult,
    ExecutionIntent,
    MarketSnapshotMeta,
    PermissionResult,
    Reason,
)

__all__ = [
    "AccountFacts",
    "AccountMode",
    "BreakState",
    "Candle",
    "CandleSequenceState",
    "CandleSeries",
    "ControllerLease",
    "DataQuality",
    "DemoGuardResult",
    "Direction",
    "EntityId",
    "ExecutionIntent",
    "ExecutionState",
    "ExtensionState",
    "HardDecision",
    "MarketSnapshot",
    "MarketSnapshotMeta",
    "MarketState",
    "MomentumPhase",
    "NewsSafetyState",
    "OpportunityStage",
    "PermissionResult",
    "PositionOwnership",
    "Quote",
    "Reason",
    "RiskState",
    "RuntimeRole",
    "StrategyFamily",
    "StructureState",
    "SwingRole",
    "SwingSide",
    "SymbolSpec",
    "Timeframe",
    "TradeManagerAction",
    "VolatilityState",
]
